version: '3'

services:
  mysql:
    image: 'mysql:8'
    platform: linux/x86_64
    restart: always
    volumes:
      - ecommerce-project:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123123'
    command: mysqld --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  ecommerce-project: